### ISSUE TITLE
Link this as sub-module within cortx-motr

### ISSUE THREAD

**Issue by johnbent** [Seagate/m0client-sample-apps#13]
Just to make sure that the community has visibility into this repo, I suggest we add it as a submodule into cortx-motr.

@andriytk , you cool with that?
@shailesh-vaidya , will this break the recursive clone / build?

If both of you are good, we can ask @gauravchaudhari02 to do the needful.

**Comment by andriytk** [comment]
@johnbent sub-links in git are usually used for the packages on which the package depends on. Motr does not depend on this package (rather vice versa). So there is no point in such sub-link.

I think just mentioning it in some Motr doc as an example of Motr client apps is more than enough. You can open an issue in Motr for this, not here. (Because the change you want to be done is in Motr, not here.)
